[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "5G-For-CS-Grads"
authors = [{name = "Santosh Ganji", email = "shotsan@pm.me"}]
dynamic = ["version", "description"]
